spring:
  datasource:
    url: jdbc:mysql://localhost:3306/careermate
    username: root
    password:
    dirver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

saram-in:
  access-key: 4V9bh96sWlnzkKL77umNEeAjJ0LFCRiiKqX0uTu7NnhMa2mGG
